# ============================
# Cấu hình Server
# ============================
server.port=9000
server.max_threads=10

# ============================
# Cấu hình Database (MySQL)
# ============================
database.url=jdbc:mysql://localhost:3307/warehouse_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
database.username=root
database.password=
